### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by gadieichhorn** [ANierbeck/Karaf-Microservices-Tooling#1]
The mvn clean install process was successful and I have the images on my host

> docker images
> REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
> anierbeck/javaland-karaf-docker   0.4                 932695ed3269        29 minutes ago      204.8 MB
> jeanblanchard/java                jdk-8               4a0583d4c8c7        4 weeks ago         170.4 MB

when I try to run the images I get an error.

> docker run anierbeck/javaland-karaf-docker:0.4
> /bin/sh: /opt/karaf/apache-karaf/bin/karaf: Permission denied

I run on win 10 and docker 1.12.0

thanks.

**Comment by ANierbeck** [comment]
As I don't have a win 10 box, I tried on mac with 1.12.1 (docker) and it works for me. 

_mvn clean install_ is successful and also _mvn docker:start_ as _mvn docker:stop_

Nothing I can do about ... sorry.

**Comment by gadieichhorn** [comment]
Thanks.
