### ISSUE TITLE
BUILD Failure

### ISSUE THREAD

**Issue by PrasBiswas2016** [ANierbeck/Karaf-Microservices-Tooling#2]
Failed to execute goal org.jolokia.docker-maven-plugin. Execution default-cli of org.jolokia.docker-maven-plugin failed: No url given, no DOCKER_HOST environment  variable and no read/writable '/var/run/docker.sock'

When I do this:

Karaf - Microservice Docker
## mvn docker:start  

Windows 10 docker

**Comment by ANierbeck** [comment]
Sounds like an Windows 10 issue ... did you check if your docker env is properly configured?

On Mac there is no such issue reproducible.

**Comment by ivanzor** [comment]
Hello.
I wonna use your docker container but have problems when start it.
1) docker pull anierbeck/javaland-karaf-docker                                                                                                             root@debian
Using default tag: latest
Pulling repository docker.io/anierbeck/javaland-karaf-docker
Tag latest not found in repository docker.io/anierbeck/javaland-karaf-docker
Ok, I pull with -a and then all your docker containers are in my local hub.

2) When I start it, docker can't see it localy and try to load it.
docker run anierbeck/javaland-karaf-docker                                                                                                              root@debian
Unable to find image 'anierbeck/javaland-karaf-docker:latest' locally
Pulling repository docker.io/anierbeck/javaland-karaf-docker
docker: Tag latest not found in repository docker.io/anierbeck/javaland-karaf-docker.

can you help me?

**Comment by ANierbeck** [comment]
There is no latest tag, it's 0.3, see https://hub.docker.com/r/anierbeck/javaland-karaf-docker/tags/

**Comment by ivanzor** [comment]
I write that I used -a to donwload ALL to my local hub, and then try to start.

**Comment by ANierbeck** [comment]
doing *docker run* 
works like a charm: 

╰─$ docker run anierbeck/javaland-karaf-docker:0.3
Unable to find image 'anierbeck/javaland-karaf-docker:0.3' locally
0.3: Pulling from anierbeck/javaland-karaf-docker
a3ed95caeb02: Pull complete
77c6c00e8b61: Pull complete
61b90c8094ba: Pull complete
96b542aa9fae: Pull complete
91e17655d143: Pull complete
bdd6cb71a978: Pull complete
03f992b49be8: Pull complete
9aebcd163813: Pull complete
9c62beaef78e: Pull complete
47e93e7d9352: Pull complete
Digest: sha256:40a8e7ce72e9b4b9be33bfd5499eae68d8b30257402be91a183dbdba74420f3a
Status: Downloaded newer image for anierbeck/javaland-karaf-docker:0.3
Listening for transport dt_socket at address: 5005
        __                  __                    __
       / /___ __   ______ _/ /   ____ _____  ____/ /
  __  / / __ `/ | / / __ `/ /   / __ `/ __ \/ __  /
 / /_/ / /_/ /| |/ / /_/ / /___/ /_/ / / / / /_/ /
 \____/\__,_/ |___/\__,_/_____/\__,_/_/ /_/\__,_/

  Apache Karaf - JavaLand Edition  (3.0.3-SNAPSHOT)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or 'osgi:shutdown' to shutdown Karaf.

karaf@root>
