### ISSUE TITLE
Doesn't build in Linux Debian or Windows, only Mac

### ISSUE THREAD

**Issue by PrasBiswas2016** [ANierbeck/Karaf-Microservices-Tooling#3]
CMD: docker pull anierbeck/javaland-karaf-docker
Using default tag: latest

Pulling repository docker.io/anierbeck/javaland-karaf-docker
Tag latest not found in repository docker.io/anierbeck/javaland-karaf-docker

??? what is the tag?

~ # docker run -d -it anierbeck/javaland-karaf-docker --name karaf                                                                                      root@debian
Unable to find image 'anierbeck/javaland-karaf-docker:latest' locally
Pulling repository docker.io/anierbeck/javaland-karaf-docker
I have locally 3 images

REPOSITORY							Tag		IMAGE ID			CREATED					SIZE
anierbeck/javaland-karaf-docker   0.3       008a85163392        15 months ago          197 MB
anierbeck/javaland-karaf-docker   0.2       f88ba7e20593        15 months ago          197 MB
anierbeck/javaland-karaf-docker   0.1       4fcd152f23b3        15 months ago          192.4 MB

------------------------------------------------------------

However, when I start it, docker can't find it locally...the same error as in windows as reproduced below:

===================================================================

**In Windows**
Tag latest not found in repository docker.io/anierbeck/javaland-karaf-docker

??? what is the tag?

I downloaded from GIT into local folder, then

When I run mvn docker:start in folder Karaf-Microservices-Tooling\
with **DOCKER_HOST variable pointing to localhost:2375**

[INFO] Karaf-Microservice-Tooling ......................... SKIPPED
[INFO] karaf-deployer-maven-plugin ........................ SKIPPED
[INFO] Karaf-Service-Runtime-feature ...................... SKIPPED
[INFO] Karaf-Service-Docker ............................... SKIPPED

[INFO] BUILD FAILURE

[ERROR] **No plugin found for prefix 'docker' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\....\.m2\repository), central (https://repo.maven.apache.org/maven2)]** -> [Help 1]

[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml 
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] [ERROR] **No plugin found for prefix 'docker' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Pras Biswas\.m2\repository), central (https://repo.maven.apache.org/maven2)] ->** [Help 1]

=====================================================================

When I run in Karaf-Microservices-Tooling\Karaf-Service-Docker folder
-- with **DOCKER_HOST variable pointing to localhost:2375**

[INFO] --- docker-maven-plugin:0.13.4:start (default-cli) @ Karaf-Service-Docker ---
[ERROR][31mDOCKER> URI does not specify a valid host name: localhost:2375/v1.17/images/anierbeck%2Fjavaland-karaf-docker%3A0.4/json m
[ERROR] [31mDOCKER> Error occurred during container startup, shutting down...[m
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.287 s
[INFO] Finished at: 2016-12-11T12:24:24-05:00
[INFO] Final Memory: 12M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] **Failed to execute goal org.jolokia:docker-maven-plugin:0.13.4:start (default-cli) on project Karaf-Service-Docker: I/O Error: Unable to check image [anierbeck/javaland-karaf-docker:0.4] ->** [Help 1]

=====================================================================
When I run in Karaf-Microservices-Tooling\Karaf-Service-Docker folder
-- with **DOCKER_HOST variable pointing to tcp://localhost:2375**

[INFO] --- docker-maven-plugin:0.13.4:start (default-cli) @ Karaf-Service-Docker ---
[INFO] [32mDOCKER> ... Pulling repository docker.io/anierbeck/javaland-karaf-docker[m
[ERROR] [31mDOCKER> Tag 0.4 not found in repository docker.io/anierbeck/javaland-karaf-docker [m
[ERROR] [31mDOCKER> Error occurred during container startup, shutting down...[m
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.634 s
[INFO] Finished at: 2016-12-11T12:28:44-05:00
[INFO] Final Memory: 12M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] **Failed to execute goal org.jolokia:docker-maven-plugin:0.13.4:start (default-cli) on project Karaf-Service-Docker: I/O Error: Unable to pull 'anierbeck/javaland-karaf-docker:0.4' ->** [Help 1]
[ERROR]

=====================================================================
When I run in Karaf-Microservices-Tooling\Karaf-Service-Docker folder
-- without DOCKER_HOST variable

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.674 s
[INFO] Finished at: 2016-12-11T12:26:43-05:00
[INFO] Final Memory: 13M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] **Failed to execute goal org.jolokia:docker-maven-plugin:0.13.4:start (default-cli) on project Karaf-Service-Docker: Execution default-cli of goal org.jolokia:docker-maven-plugin:0.13.4:start failed: No url given, no DOCKER_HOST environment variable and no read/writable '/var/run/docker.sock' ->** [Help 1]
[ERROR]

The same issue was reproduced in Ubuntu.

Please fix these issues in Windows 10 and in Debian / Linux

This only seems to work on Mac BSD

**Comment by ANierbeck** [comment]
First of all, it's version 0.3 available at hub.docker.com, not latest. 
Second seems like your user isn't capable of using docker. 
Try with a sudo docker and you'll see those messages gone. 
With Ubuntu make sure you have docker configured correctly to work with your current user, 
per default it's only available for root users.

**Comment by PrasBiswas2016** [comment]
No, you provided wrong instructions.

This doesn't work:

The Karaf-Service-Docker module contains a ready to use Apache Karaf server as basis for the Microservices samples. To start this Docker image just issue:

**mvn docker:start**
 
to start the docker image.

This works:
**docker run anierbeck/javaland-karaf-docker:0.3**
_with :0.3_
put the number

**Comment by PrasBiswas2016** [comment]
Also note- 

	 docker run -it anierbeck/javaland-karaf-docker:0.3

Use the **-it** switch to enter Interactively in shell mode - starts the container in interactive mode so that Ctrl-C/D and the shell function properly

**Comment by ANierbeck** [comment]
Well ... I never said the mvn docker:start will leave you with an interactive shell, it certainly doesn't!

still mvn docker:start still works very well for me, so the problem is on your side, not mine. 

If you want to have an interactive shell with mvn docker:start make sure to connect to the opened ssh port at 8101.

**Comment by PrasBiswas2016** [comment]
I found an easy docker image that works with one command to start karaf:

 **docker run -it mkroli/karaf:latest**

Instead of trying to starting it from mvn: and failing on Windows and other Linux distros
Which has got nothing to do with sudo: or runas: permissions

>>still mvn docker:start still works very well for me, so the problem is on your side, not mine.


That's why we have **docker** - to negate all O/S and System dependencies
